import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useRouter } from 'next/router'

const Home: NextPage = () => {
  const router = useRouter()
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
            ArcGIS Online 
        </h1>
        
        <div className={styles.grid} >
        <button type="button" onClick={() => router.push('/google')}>
          Google Map
        </button>
        <button type="button" onClick={() => router.push('/mapbox')}>
          MapBox
        </button>
        <button type="button" onClick={() => router.push('/maptiler')}>
          Map Tiler
        </button>
        <button type="button" onClick={() => router.push('/zeemaps')}>
          Zee Maps
        </button>
        <button type="button" onClick={() => router.push('/google')}>
          Google Map
        </button>
        <button type="button" onClick={() => router.push('/arcgis')}>
          ArcGis Online
        </button>
      
      
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="#"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by Enérgica City
         
        </a>
      </footer>
    </div>
  )
}

export default Home
