import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { useRouter } from 'next/router';
import { Container } from '@chakra-ui/react';

const Home: NextPage = () => {
  const router = useRouter();
  return (
    <>
      <Container>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>TESTEO DE MAPAS</h1>
          <button type="button" onClick={() => router.push('/mapbox')}>
            MapBox
          </button>

          <button type="button" onClick={() => router.push('/google')}>
            Google Map
          </button>

          <button type="button" onClick={() => router.push('/google')}>
            Here Maps
          </button>
        </main>
      </Container>
      <footer className={styles.footer}>
        <a href="#" target="_blank" rel="noopener noreferrer">
          Powered by Enérgica City
        </a>
      </footer>
    </>
  );
};

export default Home;
