import React, { useRef, useEffect, useState } from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { useRouter } from 'next/router';
import ReactMapboxGl, { Layer, Feature } from 'react-mapbox-gl';
import 'mapbox-gl/dist/mapbox-gl.css';

const Home: NextPage = () => {
  const router = useRouter();
  const Map = ReactMapboxGl({
    accessToken: `${process.env.NEXT_PUBLIC_MAPBOX}`,
  });

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <h1 className={styles.title}>MapBox</h1>
      </header>
      <nav className={styles.grid}>
        <button type="button" onClick={() => router.push('/google')}>
          Google Map
        </button>
        <button type="button" onClick={() => router.push('/mapbox')}>
          MapBox
        </button>

        <button type="button" onClick={() => router.push('/google')}>
          Google Map
        </button>
      </nav>
      <main className={styles.main}>
        <Map
          style="mapbox://styles/mapbox/streets-v9"
          containerStyle={{
            height: '40vh',
            width: '40vw',
          }}
        >
          <Layer
            type="symbol"
            id="marker"
            layout={{ 'icon-image': 'marker-15' }}
          >
            <Feature coordinates={[-0.481747846041145, 51.3233379650232]} />
          </Layer>
        </Map>
      </main>

      <footer className={styles.footer}>
        <a href="#" target="_blank" rel="noopener noreferrer">
          Powered by Enérgica City
        </a>
      </footer>
    </div>
  );
};

export default Home;
